### ISSUE TITLE
NullPointerException a master-ben

### ISSUE THREAD

**Issue by szum7** [SzFMV2017-Osz/AutomatedCar#221]
Mintha más nem panaszkodott volna, de nekem NullPointerException-el indul a master-ben lévő kód. A világ megjelenik az autóval, de semmi irányítás nem működik, csak áll. Másnál ez nem jön elő? (Buildek végigmennek, hibátlanul.)
NetBeans IDE 8.1-et használok.

```
Exception in thread "main" java.lang.NullPointerException
	at hu.oe.nik.szfmv.visualisation.Dashboard.refreshDisplayedValues(Dashboard.java:136)
	at hu.oe.nik.szfmv.visualisation.Dashboard.loop(Dashboard.java:49)
	at hu.oe.nik.szfmv.automatedcar.bus.VirtualFunctionBus.loop(VirtualFunctionBus.java:52)
	at hu.oe.nik.szfmv.automatedcar.AutomatedCar.drive(AutomatedCar.java:64)
	at hu.oe.nik.szfmv.Main.mainLoop(Main.java:80)
	at hu.oe.nik.szfmv.Main.main(Main.java:40)
```

**Comment by pintergreg** [comment]
Nekem NetBeansben is jó (8.2), de azt hiszem legközelebb ki lesz tiltva az IDEA GUI designer-e, mert nem platformfüggetlen és csak a szívás van vele.

**Comment by szum7** [comment]
@pintergreg Mit javasolsz, hogyan tudnám megoldani a hibát?

**Comment by pintergreg** [comment]
Sajnos nem tudtam reprodukálni a jelenséget, így megoldást sem tudok rá adni.
* Nézd meg, hogy a maven alkamazott-e minden módosítást ami a pom.xml-ben történt. Ezt nem tudom NetBeans-ben hogy lehet kikényszeríteni
* Próbálj egy clean & build-et
* Ez elég ötletszerű, de érdekelne mi van ha letörlöd a dashboard.form-ot
* Nézd meg, hogy IDEÁ-ban fordul-e

**Comment by szum7** [comment]
Van a Dashboard.java fájlban egy _LastRoadSignLabel_ változó ami sosincs inicializálva, de a _refreshDisplayedValues()_ metódusban mégis hív rá egy _LastRoadSignLabel.setText(lastRoadSignValue);_ -t.

Amennyire értem, ez valami generált osztály. Egyelőre csak így oldottam meg:
```
private void refreshDisplayedValues() {
    GasPedalLabel.setText(gasPedalValue);
    BrakePedalLabel.setText(brakePedalValue);
    TransmissionLabel.setText(transmissionValue);
    RevolutionLabel.setText(revolutionValue);
    SpeedLabel.setText(speedValue);
    SteeringWheelLabel.setText(steeringWheelValue);
    PosXLabel.setText(posXValue);
    PosYLabel.setText(posYValue);
    IndexLabel.setText(indexValue);
    if(LastRoadSignLabel != null)
        LastRoadSignLabel.setText(lastRoadSignValue);
}
```

**Comment by pintergreg** [comment]
Ha ez megoldja akkor legyen így. Az táblafelismerés a @SzFMV2017-Osz/team3 feladata, ott ment valami félre.
Egyébként biztos, hogy a(z aktuális) master-en vagy? Én nem tudtam ezt reprodukálni. Csinálsz is valamit az autóval, amitől előjön, vagy simán a futtatásnál már érkezik az exception?
Az autó nálam egyébként vezérelhető (bár a kirajzolt autó ellentétes irányba fordul), a nulla gomb megnyomására bekapcsol a szenzor megjelenítés és az segít az autó valós helyzetének megállapításában.

**Comment by szum7** [comment]
NetBeans IDE 8.2-t használok, clone-al tisztán leszedem a master ágat, clean and build, majd futtatom a Main-t. A hiba 1-2 másodperc után jelentkezik (amíg felépülnek a JPanelek gondolom). Az autó egyáltalán nem is vezérelhető, bár a pályával együtt megjelenik.

A fent írt hibajavításommal megtoldva úgy működik ahogy itt írtad.
